name: "tiktok_recipe_intelligence"
version: "1.0.0"
config-version: 2

profile: "tiktok_recipe_intelligence"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "{{ env_var('DBT_TARGET_PATH', 'target') }}"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tiktok_recipe_intelligence:
    staging:
      +materialized: view
    marts:
      +materialized: view
