from __future__ import annotations

import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "data" / "raw"
OUTPUT = RAW_DIR / "social_recipe_verified_real_videos.csv"
EXISTING_TIKTOK = RAW_DIR / "tiktok_food_exact_captions_strict_22_rows_with_louloukitchen.csv"

CSV_COLUMNS = [
    "TITLE",
    "DESCRIPTION",
    "URL_TIKTOK",
    "PLATFORM",
    "CONTENT_ID",
    "CREATOR_USERNAME",
    "SOURCE_PLATFORM_URL",
    "RECIPE_LANGUAGE_HINT",
    "CUISINE_HINT",
    "MAIN_INGREDIENT_HINT",
    "DESCRIPTION_IS_PARTIAL",
    "DATA_ORIGIN",
    "VERIFICATION_SOURCE_URL",
]


VERIFIED_ROWS = [
    {
        "TITLE": "Gazpacho de melocoton",
        "DESCRIPTION": "Gazpacho de melocoton con tomate triturado, melocoton, ajo, pimiento, cebolla, aceite de oliva, vinagre de manzana y sal. Triturar los ingredientes hasta obtener una sopa fria suave y ajustar acidez y sal al gusto.",
        "URL_TIKTOK": "https://youtube.com/shorts/KO70AV4J52s?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "KO70AV4J52s",
        "CREATOR_USERNAME": "antoniasevilla",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/KO70AV4J52s?feature=share",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "spanish",
        "MAIN_INGREDIENT_HINT": "peach",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/ar/recetas/16616290-gazpacho-de-melocoton",
    },
    {
        "TITLE": "Gofres de cacao sin gluten",
        "DESCRIPTION": "Gofres de cacao sin gluten preparados mezclando los ingredientes en un bol hasta conseguir una masa homogenea. Cocinar en moldes de silicona al microondas o en gofrera y enfriar antes de servir.",
        "URL_TIKTOK": "https://youtube.com/shorts/s7P1eEKUrfo?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "s7P1eEKUrfo",
        "CREATOR_USERNAME": "antoniasevilla",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/s7P1eEKUrfo?feature=share",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "dessert",
        "MAIN_INGREDIENT_HINT": "cocoa",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/25006059",
    },
    {
        "TITLE": "Mandorle e nocciole al cioccolato",
        "DESCRIPTION": "Dolcetti italiani con mandorle, nocciole tostate e cioccolato fondente. Tostare la frutta secca, sciogliere il cioccolato a bagnomaria, mescolare tutto e formare piccoli mucchietti su carta forno.",
        "URL_TIKTOK": "https://youtube.com/shorts/PhOAEtqplcU?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "PhOAEtqplcU",
        "CREATOR_USERNAME": "lucia_fiale",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/PhOAEtqplcU?feature=share",
        "RECIPE_LANGUAGE_HINT": "it",
        "CUISINE_HINT": "italian dessert",
        "MAIN_INGREDIENT_HINT": "almonds",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://www.ilsipontino.net/mandorle-e-nocciole-atterrate-al-cioccolato-la-video-ricetta/",
    },
    {
        "TITLE": "Pasta fresca agli spinaci con due ingredienti",
        "DESCRIPTION": "Pasta fresca verde fatta con farina e spinaci. Frullare farina e spinaci fino a ottenere un impasto compatto, tagliare piccoli pezzi direttamente in acqua bollente e condire con pesto di spinaci, noci, parmigiano, aglio, olio e sale.",
        "URL_TIKTOK": "https://youtube.com/shorts/-7G3u2VOH9c",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "-7G3u2VOH9c",
        "CREATOR_USERNAME": "lericettedisimo",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/-7G3u2VOH9c",
        "RECIPE_LANGUAGE_HINT": "it",
        "CUISINE_HINT": "italian",
        "MAIN_INGREDIENT_HINT": "spinach",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://blog.giallozafferano.it/lericettedisimo/ricetta-pasta-fresca-agli-spinaci/",
    },
    {
        "TITLE": "Tramezzini al salmone",
        "DESCRIPTION": "Tramezzini farciti con pane morbido, formaggio spalmabile, maionese, uovo sodo, capperi, cipolla, salmone affumicato, sale e pepe. Mescolare la crema, spalmarla sul pane, aggiungere verdura e tagliare in diagonale.",
        "URL_TIKTOK": "https://youtube.com/shorts/eduFflIOaI8?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "eduFflIOaI8",
        "CREATOR_USERNAME": "cookist",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/eduFflIOaI8?feature=share",
        "RECIPE_LANGUAGE_HINT": "it",
        "CUISINE_HINT": "italian appetizer",
        "MAIN_INGREDIENT_HINT": "salmon",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://video.cookist.it/video/an/Y5CD8uSwymkCBtCP",
    },
    {
        "TITLE": "Cookies burro di arachidi e marmellata",
        "DESCRIPTION": "Cookies con burro di arachidi, burro morbido, zucchero di canna, farina, tuorli, sale, bicarbonato e marmellata. Lavorare burri e zucchero, aggiungere tuorli e farina, incorporare marmellata e cuocere in forno.",
        "URL_TIKTOK": "https://youtube.com/shorts/XgYGI9hf170?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "XgYGI9hf170",
        "CREATOR_USERNAME": "chiarasbakery",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/XgYGI9hf170?feature=share",
        "RECIPE_LANGUAGE_HINT": "it",
        "CUISINE_HINT": "dessert",
        "MAIN_INGREDIENT_HINT": "peanut butter",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://www.chiarasbakery.it/ricetta-cookies-burro-di-arachidi-e-marmellata/",
    },
    {
        "TITLE": "Melanzane ripiene senza uova",
        "DESCRIPTION": "Melanzane ripiene leggere con aglio, prezzemolo, basilico, capperi, tonno, olio extravergine, olive, pepe nero, peperoncino e pangrattato opzionale. Svuotare e farcire le melanzane, poi cuocere fino a gratinatura.",
        "URL_TIKTOK": "https://youtube.com/shorts/CIyWhEWB3Dg?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "CIyWhEWB3Dg",
        "CREATOR_USERNAME": "misterkitchen",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/CIyWhEWB3Dg?feature=share",
        "RECIPE_LANGUAGE_HINT": "it",
        "CUISINE_HINT": "italian keto",
        "MAIN_INGREDIENT_HINT": "eggplant",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://misterkitchen.altervista.org/melanzane-ripiene-senza-uova-ricetta-chetogenica/",
    },
    {
        "TITLE": "Rolls de espinaca",
        "DESCRIPTION": "Rolls saludables con espinaca, huevos, almidon de maiz, leche, aceite de oliva, sal y pimienta. Preparar la masa verde, cocinarla fina y rellenar con zanahoria, tomate, choclo y palta.",
        "URL_TIKTOK": "https://youtube.com/shorts/o2VJ3iwH_Lw",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "o2VJ3iwH_Lw",
        "CREATOR_USERNAME": "laanonima",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/o2VJ3iwH_Lw",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "healthy",
        "MAIN_INGREDIENT_HINT": "spinach",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://mobilenikappviews.laanonimaws.com/empresa/recetas/rolls-de-espinaca",
    },
    {
        "TITLE": "Strangolapreti ricotta e spinaci con speck",
        "DESCRIPTION": "Gnocchi tradizionali con ricotta, spinaci e speck croccante, serviti con burro e salvia. Preparare l'impasto morbido, formare gli strangolapreti, lessarli e saltarli con il condimento.",
        "URL_TIKTOK": "https://youtube.com/shorts/z0-H6IdgHmc?si=QGtM120ZM-r8ye7k",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "z0-H6IdgHmc",
        "CREATOR_USERNAME": "animaincucina",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/z0-H6IdgHmc?si=QGtM120ZM-r8ye7k",
        "RECIPE_LANGUAGE_HINT": "it",
        "CUISINE_HINT": "italian",
        "MAIN_INGREDIENT_HINT": "spinach",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://www.animaincucina.it/ricetta-strangolapreti-ricotta-e-spinaci-con-speck-ricetta-tradizionale-al-burro-e-salvia/",
    },
    {
        "TITLE": "Salade de poulet au curry",
        "DESCRIPTION": "Salade zero dechet avec chair de poulet, oeuf dur, mayonnaise, curry indien, jus de citron, herbes hachees, salade et pain. Effilocher le poulet, lier avec la sauce curry et garnir un bun grille.",
        "URL_TIKTOK": "https://www.instagram.com/reel/C1VKeyvtUWy/",
        "PLATFORM": "instagram",
        "CONTENT_ID": "C1VKeyvtUWy",
        "CREATOR_USERNAME": "gregcookandroll",
        "SOURCE_PLATFORM_URL": "https://www.instagram.com/reel/C1VKeyvtUWy/",
        "RECIPE_LANGUAGE_HINT": "fr",
        "CUISINE_HINT": "french",
        "MAIN_INGREDIENT_HINT": "chicken",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://www.cookandroll.eu/archives/2024/02/06/40198186.html",
    },
    {
        "TITLE": "Magret de canard seche au piment Niora",
        "DESCRIPTION": "Magret de canard seche avec salage par impregnation, epices et piment Niora legerement fume. Emballer serre ou sous vide, laisser maturer puis secher selon la methode indiquee.",
        "URL_TIKTOK": "https://www.instagram.com/reel/DGLb53PIXrj/",
        "PLATFORM": "instagram",
        "CONTENT_ID": "DGLb53PIXrj",
        "CREATOR_USERNAME": "gregcookandroll",
        "SOURCE_PLATFORM_URL": "https://www.instagram.com/reel/DGLb53PIXrj/",
        "RECIPE_LANGUAGE_HINT": "fr",
        "CUISINE_HINT": "french charcuterie",
        "MAIN_INGREDIENT_HINT": "duck",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://www.cookandroll.eu/2025/03/magret-de-canard-seche-au-piment-niora.html",
    },
    {
        "TITLE": "Tahdig Persian rice",
        "DESCRIPTION": "Tahdig with basmati rice, butter, olive oil, water, saffron and salt. Rinse and soak the rice, parboil until the outside softens, then steam with fat and saffron to form a crisp golden crust.",
        "URL_TIKTOK": "https://instagram.com/p/CLXtUlPn8U2/",
        "PLATFORM": "instagram",
        "CONTENT_ID": "CLXtUlPn8U2",
        "CREATOR_USERNAME": "el_pinche_jack",
        "SOURCE_PLATFORM_URL": "https://instagram.com/p/CLXtUlPn8U2/",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "persian",
        "MAIN_INGREDIENT_HINT": "rice",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/eng/recipes/14834447",
    },
    {
        "TITLE": "Fresh tomato salsa",
        "DESCRIPTION": "Fresh tomato salsa with ripe tomatoes, onion, jalapenos, lime, olive oil, cilantro, cumin, salt and pepper. Pulse the ingredients in a food processor until chunky and bright.",
        "URL_TIKTOK": "https://instagram.com/p/YdHoRiFg98/",
        "PLATFORM": "instagram",
        "CONTENT_ID": "YdHoRiFg98",
        "CREATOR_USERNAME": "aggieskitchen",
        "SOURCE_PLATFORM_URL": "https://instagram.com/p/YdHoRiFg98/",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "mexican",
        "MAIN_INGREDIENT_HINT": "tomato",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://aggieskitchen.com/fresh-tomato-salsa/",
    },
    {
        "TITLE": "Maryland crab dip",
        "DESCRIPTION": "Crab dip with softened cream cheese, mayo, sour cream, whole grain mustard, Old Bay hot sauce, Old Bay seasoning, roasted garlic, smoked cheddar, Gruyere, lemon and lump crab. Mix and bake until hot and bubbling.",
        "URL_TIKTOK": "https://www.tiktok.com/t/ZTFkHypMC/",
        "PLATFORM": "tiktok",
        "CONTENT_ID": "ZTFkHypMC",
        "CREATOR_USERNAME": "tinekeyounger",
        "SOURCE_PLATFORM_URL": "https://www.tiktok.com/@tinekeyounger",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "american",
        "MAIN_INGREDIENT_HINT": "crab",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_article",
        "VERIFICATION_SOURCE_URL": "https://forums.extremeravens.com/topic/32508-ravens-insider-meet-tini-younger-a-social-media-chef-and-ravens-fan-with-over-9-million-followers/",
    },
    {
        "TITLE": "Buffalo chicken dip",
        "DESCRIPTION": "Buffalo chicken dip with seasoned chicken breasts, smoked Gouda, cheddar, cream cheese, ranch or blue cheese, roasted garlic and chives. Cook the chicken, shred it, mix with cheeses and bake until melted.",
        "URL_TIKTOK": "https://www.tiktok.com/t/ZP8Rm8XoV/",
        "PLATFORM": "tiktok",
        "CONTENT_ID": "ZP8Rm8XoV",
        "CREATOR_USERNAME": "tinekeyounger",
        "SOURCE_PLATFORM_URL": "https://www.tiktok.com/@tinekeyounger",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "american",
        "MAIN_INGREDIENT_HINT": "chicken",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_article",
        "VERIFICATION_SOURCE_URL": "https://forums.extremeravens.com/topic/32508-ravens-insider-meet-tini-younger-a-social-media-chef-and-ravens-fan-with-over-9-million-followers/",
    },
]


ADDITIONAL_VERIFIED_ROWS = [
    {
        "TITLE": "Spaghetti with zucchini cream and clams",
        "DESCRIPTION": "Spanish pasta recipe with spaghetti, zucchini cream, clams, chili, olive oil and seasoning. Cook the pasta, blend or cook down the zucchini into a sauce, combine with clams and finish warm.",
        "URL_TIKTOK": "https://youtube.com/shorts/7uQqLlspYF8?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "7uQqLlspYF8",
        "CREATOR_USERNAME": "antoniasevilla",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/7uQqLlspYF8?feature=share",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "spanish pasta",
        "MAIN_INGREDIENT_HINT": "zucchini",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/25062255",
    },
    {
        "TITLE": "Broccoli and egg breakfast patties",
        "DESCRIPTION": "Healthy breakfast with broccoli, onion, cheese, egg whites and egg yolks. Blanch and chop broccoli, mix with onion, cheese and whites, shape patties, add yolks in the center and cook covered.",
        "URL_TIKTOK": "https://youtube.com/shorts/yH2zOqK-9cI?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "yH2zOqK-9cI",
        "CREATOR_USERNAME": "OnlyProvenRecipes",
        "SOURCE_PLATFORM_URL": "https://www.youtube.com/@OnlyProvenRecipes",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "healthy breakfast",
        "MAIN_INGREDIENT_HINT": "broccoli",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/eng/recipes/25346846",
    },
    {
        "TITLE": "Turkey legs and potatoes in the oven",
        "DESCRIPTION": "Spanish oven dish with turkey legs, potatoes, onion, green pepper, olive oil and a parsley, thyme, paprika, garlic and tomato paste marinade. Roast wrapped turkey with seasoned potatoes until tender and browned.",
        "URL_TIKTOK": "https://youtube.com/shorts/jAip-FCL2og?si=0jAIQa4YeILW6AKX",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "jAip-FCL2og",
        "CREATOR_USERNAME": "poesiadefogon",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/jAip-FCL2og?si=0jAIQa4YeILW6AKX",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "spanish home cooking",
        "MAIN_INGREDIENT_HINT": "turkey",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/24791418",
    },
    {
        "TITLE": "Gnocchi with textured soy and pisto",
        "DESCRIPTION": "Vegetarian Spanish-style dish with gnocchi, textured soy, vegetable stock, white wine, pisto, garlic, turmeric, pepper, thyme and parsley. Hydrate soy in seasoned broth, add pisto, then cook gnocchi briefly.",
        "URL_TIKTOK": "https://youtube.com/shorts/_E5WhrRcp5g?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "_E5WhrRcp5g",
        "CREATOR_USERNAME": "antoniasevilla",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/_E5WhrRcp5g?feature=share",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "spanish vegetarian",
        "MAIN_INGREDIENT_HINT": "gnocchi",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/25057898",
    },
    {
        "TITLE": "Healthy banana oat dessert",
        "DESCRIPTION": "No-flour dessert with oats, almonds, peanuts, raisins, prunes, cranberries, sesame, cocoa, banana, honey and dark chocolate. Mix chopped nuts and fruit with mashed banana, bake, then glaze with chocolate.",
        "URL_TIKTOK": "https://youtube.com/shorts/2udJVgu2V2Y",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "2udJVgu2V2Y",
        "CREATOR_USERNAME": "OnlyProvenRecipes",
        "SOURCE_PLATFORM_URL": "https://www.youtube.com/@OnlyProvenRecipes",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "healthy dessert",
        "MAIN_INGREDIENT_HINT": "banana",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/eng/recipes/25109884",
    },
    {
        "TITLE": "Individual chocolate cold dessert",
        "DESCRIPTION": "Cold Spanish dessert with chocolate cream, chocolate chip cookies, chantilly mix, soy drink or milk, chocolate sprinkles and homemade strawberry jam. Layer cream, cookies, jam and whipped topping in small glasses.",
        "URL_TIKTOK": "https://youtube.com/shorts/F4UMHBuAwJ0?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "F4UMHBuAwJ0",
        "CREATOR_USERNAME": "antoniasevilla",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/F4UMHBuAwJ0?feature=share",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "dessert",
        "MAIN_INGREDIENT_HINT": "chocolate",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/25133862",
    },
    {
        "TITLE": "Shrimp shumai",
        "DESCRIPTION": "Shumai dumplings with shrimp, dried scallops, bamboo shoots, green onion, egg white, ginger, potato starch, cooking wine, sesame oil and wrappers. Mix filling until sticky, form cups and steam.",
        "URL_TIKTOK": "https://youtube.com/shorts/4KHp1857kxc",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "4KHp1857kxc",
        "CREATOR_USERNAME": "okane",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/4KHp1857kxc",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "asian",
        "MAIN_INGREDIENT_HINT": "shrimp",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/eng/recipes/17263489",
    },
    {
        "TITLE": "Individual chocolate cheesecake",
        "DESCRIPTION": "No-bake style individual cheesecake with cream cheese, dessert chocolate, sweetener, crackers and optional cream. Melt chocolate, combine with softened cheese, portion into glasses and chill.",
        "URL_TIKTOK": "https://youtube.com/shorts/u_bjRfVpCHs?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "u_bjRfVpCHs",
        "CREATOR_USERNAME": "antoniasevilla",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/u_bjRfVpCHs?feature=share",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "dessert",
        "MAIN_INGREDIENT_HINT": "cream cheese",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/25125126",
    },
    {
        "TITLE": "Sweet potato chips",
        "DESCRIPTION": "Healthy chips made with sweet potato, ginger powder, black pepper, olive oil, salt, herbs and garlic powder. Slice thinly, season with oil and spices, bake until crisp and cool fully.",
        "URL_TIKTOK": "https://youtube.com/shorts/GA3r3lOPh4Q?si=CI_cEiMK29cVAwXQ",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "GA3r3lOPh4Q",
        "CREATOR_USERNAME": "n_dieteticacabrera",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/GA3r3lOPh4Q?si=CI_cEiMK29cVAwXQ",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "healthy snack",
        "MAIN_INGREDIENT_HINT": "sweet potato",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/22587904",
    },
    {
        "TITLE": "Cuban-style pork mojo",
        "DESCRIPTION": "Caribbean pork recipe with pork shoulder or loin head, sour orange or orange-lime juice, garlic and seasonings. Marinate, slow cook or confit, then fry or brown for a crisp outside.",
        "URL_TIKTOK": "https://youtube.com/shorts/MoY4sbi806g?si=niOL1rsa_nyfXYnX",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "MoY4sbi806g",
        "CREATOR_USERNAME": "OdenColt",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/MoY4sbi806g?si=niOL1rsa_nyfXYnX",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "cuban",
        "MAIN_INGREDIENT_HINT": "pork",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/25226176",
    },
    {
        "TITLE": "Sea bass fillets with lemon and potatoes",
        "DESCRIPTION": "Spanish fish tray bake with sea bass fillets, potatoes, onion, lemon, garlic, parsley, olive oil, salt and pepper. Layer potatoes and onion, add fish and lemon, then bake until tender.",
        "URL_TIKTOK": "https://youtube.com/shorts/COXGiOS4poY?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "COXGiOS4poY",
        "CREATOR_USERNAME": "antoniasevilla",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/COXGiOS4poY?feature=share",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "spanish seafood",
        "MAIN_INGREDIENT_HINT": "sea bass",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/17044368",
    },
    {
        "TITLE": "Sarmale cabbage rolls",
        "DESCRIPTION": "Romanian cabbage rolls with mixed pork and beef mince, round rice, onion, paprika and dried herbs cooked slowly in tomato sauce. Fill cabbage leaves and simmer until tender.",
        "URL_TIKTOK": "https://youtube.com/shorts/oN8UO5hJn_E?si=HohKgK5zcAGm6cOP",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "oN8UO5hJn_E",
        "CREATOR_USERNAME": "OdenColt",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/oN8UO5hJn_E?si=HohKgK5zcAGm6cOP",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "romanian",
        "MAIN_INGREDIENT_HINT": "cabbage",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/25191905",
    },
    {
        "TITLE": "Apple cottage cheese buns",
        "DESCRIPTION": "No-yeast buns with apple, egg, salt, sugar, cottage cheese, oil, lemon zest, lemon juice, flour, baking soda, cinnamon and sugar topping. Mix soft dough, portion and bake.",
        "URL_TIKTOK": "https://youtube.com/shorts/8ej2Vbhbf6s?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "8ej2Vbhbf6s",
        "CREATOR_USERNAME": "OnlyProvenRecipes",
        "SOURCE_PLATFORM_URL": "https://www.youtube.com/@OnlyProvenRecipes",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "baking",
        "MAIN_INGREDIENT_HINT": "apple",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/eng/recipes/25148167",
    },
    {
        "TITLE": "No-knead no-yeast quick pizza",
        "DESCRIPTION": "Fast pizza with eggs, sour cream, kefir or mayonnaise, flour, baking powder and salt. Mix batter, spread on parchment, add toppings and bake until golden.",
        "URL_TIKTOK": "https://youtube.com/shorts/RGQ-4n8i9Hg",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "RGQ-4n8i9Hg",
        "CREATOR_USERNAME": "OnlyProvenRecipes",
        "SOURCE_PLATFORM_URL": "https://www.youtube.com/@OnlyProvenRecipes",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "pizza",
        "MAIN_INGREDIENT_HINT": "flour",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/eng/recipes/24943516",
    },
    {
        "TITLE": "Sausage and cheese lavash roll-ups",
        "DESCRIPTION": "Quick snack with lavash bread, sausages, grated cheese, eggs, mayonnaise, dill, salt and oil. Spread egg-cheese filling on lavash, wrap sausages and fry until crispy.",
        "URL_TIKTOK": "https://youtube.com/shorts/MWG-d5qf6PE?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "MWG-d5qf6PE",
        "CREATOR_USERNAME": "OnlyProvenRecipes",
        "SOURCE_PLATFORM_URL": "https://www.youtube.com/@OnlyProvenRecipes",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "quick snack",
        "MAIN_INGREDIENT_HINT": "sausage",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/eng/recipes/25127729",
    },
    {
        "TITLE": "Date and nut chocolate candies",
        "DESCRIPTION": "No-bake sweets with dates, peanuts or nuts, sesame seeds and dark chocolate. Toast nuts and sesame, blend dates, shape bars, fill with melted chocolate and slice after setting.",
        "URL_TIKTOK": "https://youtube.com/shorts/Ycv0PF4H7ZI?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "Ycv0PF4H7ZI",
        "CREATOR_USERNAME": "OnlyProvenRecipes",
        "SOURCE_PLATFORM_URL": "https://www.youtube.com/@OnlyProvenRecipes",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "healthy dessert",
        "MAIN_INGREDIENT_HINT": "dates",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/eng/recipes/25385376",
    },
    {
        "TITLE": "Stir fried glass noodles japchae",
        "DESCRIPTION": "Japchae-style glass noodles with vegetables, spinach and thin egg garnish. Prep vegetables separately, blanch spinach, stir fry each component and combine with noodles and seasoning.",
        "URL_TIKTOK": "https://youtube.com/shorts/Nt4gU4f34wA?si=AVNIX3mBXif0ytZ5",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "Nt4gU4f34wA",
        "CREATOR_USERNAME": "FancyNoodles",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/Nt4gU4f34wA?si=AVNIX3mBXif0ytZ5",
        "RECIPE_LANGUAGE_HINT": "en",
        "CUISINE_HINT": "korean",
        "MAIN_INGREDIENT_HINT": "glass noodles",
        "DESCRIPTION_IS_PARTIAL": "true",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/eng/recipes/24520460",
    },
    {
        "TITLE": "Zucchini pisto with tuna and octopus",
        "DESCRIPTION": "Spanish mixed dish with zucchini, onion, peppers, garlic, tomato sauce, tuna slices, cooked octopus, paprika, salt and olive oil. Cook the vegetable pisto, add tuna and serve with paprika octopus.",
        "URL_TIKTOK": "https://youtube.com/shorts/60TtcVusgCY?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "60TtcVusgCY",
        "CREATOR_USERNAME": "antoniasevilla",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/60TtcVusgCY?feature=share",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "spanish",
        "MAIN_INGREDIENT_HINT": "tuna",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/24234263",
    },
    {
        "TITLE": "Microwave rice with vegetables",
        "DESCRIPTION": "Easy microwave rice with vegetables, water or stock cube, seasoning and olive oil. Combine rice, liquid and vegetables in a microwave-safe dish and cook until the rice absorbs the liquid.",
        "URL_TIKTOK": "https://youtube.com/shorts/pvMNB6r1mkI?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "pvMNB6r1mkI",
        "CREATOR_USERNAME": "antoniasevilla",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/pvMNB6r1mkI?feature=share",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "quick rice",
        "MAIN_INGREDIENT_HINT": "rice",
        "DESCRIPTION_IS_PARTIAL": "true",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/25090556",
    },
    {
        "TITLE": "Sausages wrapped in crepes",
        "DESCRIPTION": "Simple snack with cooked chicken sausages, frozen crepes, lactose-free cheese slices, sweet mustard, ketchup and light mayonnaise. Fill, roll and heat until the cheese melts.",
        "URL_TIKTOK": "https://youtube.com/shorts/vdFVy2yepfg?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "vdFVy2yepfg",
        "CREATOR_USERNAME": "antoniasevilla",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/vdFVy2yepfg?feature=share",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "snack",
        "MAIN_INGREDIENT_HINT": "sausage",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/es/recetas/16621912",
    },
    {
        "TITLE": "Quinoa with salmon asparagus and mango",
        "DESCRIPTION": "Colorful quinoa dish with salmon, asparagus, mango, water, salt and olive oil. Cook quinoa, prepare salmon and asparagus, then combine with mango for a fresh lunch bowl.",
        "URL_TIKTOK": "https://youtube.com/shorts/vEsBhl3FOD0?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "vEsBhl3FOD0",
        "CREATOR_USERNAME": "antoniasevilla",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/vEsBhl3FOD0?feature=share",
        "RECIPE_LANGUAGE_HINT": "es",
        "CUISINE_HINT": "healthy bowl",
        "MAIN_INGREDIENT_HINT": "salmon",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/cl/recetas/25000653",
    },
    {
        "TITLE": "Lentil soup with lemon",
        "DESCRIPTION": "Arabic lentil soup with brown lentils, onions, potato, zucchini, lemon juice, dried mint, cumin, garlic and salt. Saute onion, add lentils and vegetables, pressure cook, then finish with lemon, cumin and garlic.",
        "URL_TIKTOK": "https://youtube.com/shorts/bffNu4w5m4Q?si=7ilNWJCcnLmZq2fp",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "bffNu4w5m4Q",
        "CREATOR_USERNAME": "Dinadee89",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/bffNu4w5m4Q?si=7ilNWJCcnLmZq2fp",
        "RECIPE_LANGUAGE_HINT": "ar",
        "CUISINE_HINT": "lebanese",
        "MAIN_INGREDIENT_HINT": "lentils",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/ps/%D9%88%D8%B5%D9%81%D8%A7%D8%AA/25008500",
    },
    {
        "TITLE": "Caramelized popcorn",
        "DESCRIPTION": "Arabic sweet popcorn with popcorn kernels, sugar and vegetable oil. Pop the corn, melt sugar with oil into caramel, turn off heat and coat popcorn until evenly glazed.",
        "URL_TIKTOK": "https://youtube.com/shorts/ebyRJf5XPfk?feature=share",
        "PLATFORM": "youtube_shorts",
        "CONTENT_ID": "ebyRJf5XPfk",
        "CREATOR_USERNAME": "Eng_Yosra_Shahin",
        "SOURCE_PLATFORM_URL": "https://youtube.com/shorts/ebyRJf5XPfk?feature=share",
        "RECIPE_LANGUAGE_HINT": "ar",
        "CUISINE_HINT": "sweet snack",
        "MAIN_INGREDIENT_HINT": "popcorn",
        "DESCRIPTION_IS_PARTIAL": "false",
        "DATA_ORIGIN": "verified_public_recipe_page",
        "VERIFICATION_SOURCE_URL": "https://cookpad.com/ps/%D9%88%D8%B5%D9%81%D8%A7%D8%AA/15937610-%D8%A8%D9%88%D8%B4%D8%A7%D8%B1-%D9%85%D9%83%D8%B1%D9%85%D9%84-%D8%A8%D8%A7%D9%84%D8%B3%D9%83%D8%B1-%D8%B0%D8%B1%D8%A9-%D9%81%D8%B4%D8%A7%D8%B1-%D8%A8%D8%A7%D9%84%D8%B3%D9%83%D8%B1",
    },
]


def infer_language(title: str, description: str) -> str:
    text = f"{title} {description}".lower()
    if any(token in text for token in ["receta", "ingredientes", "albondigas", "pápalo"]):
        return "es"
    if any(token in text for token in ["recette", "ingrédients", "poulet", "crème"]):
        return "fr"
    if any(token in text for token in ["ricetta", "ingredienti", "burro", "pasta fresca"]):
        return "it"
    return "en"


def extract_creator(url: str) -> str:
    match = re.search(r"tiktok\.com/@([^/]+)/", url)
    return match.group(1) if match else "unknown_creator"


def extract_content_id(url: str) -> str:
    match = re.search(r"/video/(\d+)", url)
    return match.group(1) if match else url.rstrip("/").rsplit("/", 1)[-1]


def tiktok_rows_from_existing_file() -> list[dict[str, str]]:
    if not EXISTING_TIKTOK.exists():
        return []

    rows: list[dict[str, str]] = []
    with EXISTING_TIKTOK.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            url = row["URL_TIKTOK"].strip()
            creator = extract_creator(url)
            rows.append(
                {
                    "TITLE": row["TITLE"].strip(),
                    "DESCRIPTION": row["DESCRIPTION"].strip(),
                    "URL_TIKTOK": url,
                    "PLATFORM": "tiktok",
                    "CONTENT_ID": extract_content_id(url),
                    "CREATOR_USERNAME": creator,
                    "SOURCE_PLATFORM_URL": f"https://www.tiktok.com/@{creator}",
                    "RECIPE_LANGUAGE_HINT": infer_language(row["TITLE"], row["DESCRIPTION"]),
                    "CUISINE_HINT": "",
                    "MAIN_INGREDIENT_HINT": "",
                    "DESCRIPTION_IS_PARTIAL": "false",
                    "DATA_ORIGIN": "existing_verified_tiktok_caption_file",
                    "VERIFICATION_SOURCE_URL": url,
                }
            )
    return rows


def write_csv(rows: list[dict[str, str]]) -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    seen: set[str] = set()
    deduped: list[dict[str, str]] = []
    for row in rows:
        key = row["URL_TIKTOK"]
        if key not in seen:
            seen.add(key)
            deduped.append(row)

    with OUTPUT.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        writer.writerows(deduped)


def main() -> None:
    rows = tiktok_rows_from_existing_file() + VERIFIED_ROWS + ADDITIONAL_VERIFIED_ROWS
    write_csv(rows)
    print(f"Wrote {len(rows)} candidate rows to {OUTPUT}")


if __name__ == "__main__":
    main()
