select
    raw_id as id,
    display_title as title,
    original_description,
    recovered_text,
    evidence_text,
    url_tiktok,
    recipe_language as language,
    is_vegetarian,
    cuisine_style,
    main_ingredient,
    ingredients,
    is_recipe,
    recipe_status,
    has_ingredient_list,
    has_instructions,
    caption_completeness_score,
    rejection_reason,
    final_recipe_title,
    final_recipe_text,
    final_recipe_json,
    missing_recipe_info,
    final_recipe_confidence,
    final_recipe_language,
    processing_confidence as confidence,
    model_name,
    processed_at
from {{ ref('gold_tiktok_recipe_catalog') }}
