CREATE DATABASE IF NOT EXISTS TIKTOK_PORTFOLIO_DB;
USE DATABASE TIKTOK_PORTFOLIO_DB;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS CONTROL;

CREATE OR REPLACE FILE FORMAT BRONZE.CSV_TIKTOK_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    TRIM_SPACE = TRUE
    NULL_IF = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE STAGE IF NOT EXISTS BRONZE.TIKTOK_CSV_STAGE
    FILE_FORMAT = BRONZE.CSV_TIKTOK_FORMAT;

CREATE OR REPLACE TABLE BRONZE.BRONZE_TIKTOK_RECIPES (
    RAW_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PLATFORM STRING DEFAULT 'tiktok',
    CONTENT_ID STRING,
    CREATOR_USERNAME STRING,
    TITLE STRING,
    DESCRIPTION STRING,
    DESCRIPTION_IS_PARTIAL BOOLEAN DEFAULT FALSE,
    URL_TIKTOK STRING,
    SOURCE_FILE STRING,
    RAW_PAYLOAD VARIANT,
    RECORD_HASH STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SILVER.SILVER_TIKTOK_RECIPES (
    SILVER_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RAW_ID NUMBER,
    ORIGINAL_TITLE STRING,
    ORIGINAL_DESCRIPTION STRING,
    URL_TIKTOK STRING,
    RECIPE_LANGUAGE STRING,
    IS_VEGETARIAN BOOLEAN,
    CUISINE_STYLE STRING,
    MAIN_INGREDIENT STRING,
    PROCESSING_CONFIDENCE FLOAT,
    MODEL_NAME STRING,
    LLM_RAW_RESPONSE VARIANT,
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_HASH STRING,
    CONSTRAINT UQ_SILVER_RAW UNIQUE (RAW_ID)
);

CREATE OR REPLACE TABLE CONTROL.SEEN_TIKTOK_VIDEOS (
    VIDEO_ID STRING,
    CREATOR_USERNAME STRING,
    URL_TIKTOK STRING,
    FIRST_SEEN_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_SEEN_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_SEEN_TIKTOK_VIDEO UNIQUE (VIDEO_ID)
);
