CREATE DATABASE IF NOT EXISTS TIKTOK_PORTFOLIO_DB;
USE DATABASE TIKTOK_PORTFOLIO_DB;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS CONTROL;

CREATE OR REPLACE FILE FORMAT BRONZE.CSV_TIKTOK_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    TRIM_SPACE = TRUE
    NULL_IF = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE STAGE IF NOT EXISTS BRONZE.TIKTOK_CSV_STAGE
    FILE_FORMAT = BRONZE.CSV_TIKTOK_FORMAT;

CREATE OR REPLACE TABLE BRONZE.BRONZE_TIKTOK_RECIPES (
    RAW_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PLATFORM STRING DEFAULT 'tiktok',
    CONTENT_ID STRING,
    CREATOR_USERNAME STRING,
    TITLE STRING,
    DESCRIPTION STRING,
    DESCRIPTION_IS_PARTIAL BOOLEAN DEFAULT FALSE,
    URL_TIKTOK STRING,
    SOURCE_FILE STRING,
    RAW_PAYLOAD VARIANT,
    RECORD_HASH STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SILVER.SILVER_TIKTOK_RECIPES (
    SILVER_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RAW_ID NUMBER,
    ORIGINAL_TITLE STRING,
    ORIGINAL_DESCRIPTION STRING,
    RECOVERED_TEXT STRING,
    EVIDENCE_TEXT STRING,
    EVIDENCE_QUALITY_SCORE FLOAT DEFAULT 0,
    URL_TIKTOK STRING,
    RECIPE_LANGUAGE STRING,
    IS_VEGETARIAN BOOLEAN,
    CUISINE_STYLE STRING,
    MAIN_INGREDIENT STRING,
    INGREDIENTS VARIANT,
    IS_RECIPE BOOLEAN DEFAULT TRUE,
    RECIPE_STATUS STRING DEFAULT 'partial_recipe',
    HAS_INGREDIENT_LIST BOOLEAN DEFAULT FALSE,
    HAS_INSTRUCTIONS BOOLEAN DEFAULT FALSE,
    CAPTION_COMPLETENESS_SCORE FLOAT DEFAULT 0,
    REJECTION_REASON STRING,
    FINAL_RECIPE_TITLE STRING,
    FINAL_RECIPE_TEXT STRING,
    FINAL_RECIPE_JSON VARIANT,
    MISSING_RECIPE_INFO VARIANT,
    FINAL_RECIPE_CONFIDENCE FLOAT DEFAULT 0,
    FINAL_RECIPE_LANGUAGE STRING,
    PROCESSING_CONFIDENCE FLOAT,
    MODEL_NAME STRING,
    LLM_RAW_RESPONSE VARIANT,
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_HASH STRING,
    CONSTRAINT UQ_SILVER_RAW UNIQUE (RAW_ID)
);

CREATE OR REPLACE TABLE CONTROL.SEEN_TIKTOK_VIDEOS (
    VIDEO_ID STRING,
    CREATOR_USERNAME STRING,
    URL_TIKTOK STRING,
    FIRST_SEEN_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_SEEN_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_SEEN_TIKTOK_VIDEO UNIQUE (VIDEO_ID)
);

CREATE OR REPLACE TABLE SILVER.RECIPE_CONTENT_RECOVERY (
    RECOVERY_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RAW_ID NUMBER,
    URL_TIKTOK STRING,
    CONTENT_ID STRING,
    METHOD STRING,
    RECOVERED_TEXT STRING,
    TEXT_LENGTH NUMBER,
    LANGUAGE_HINT STRING,
    CONFIDENCE FLOAT,
    ENGINE STRING,
    STATUS STRING,
    ERROR_MESSAGE STRING,
    SOURCE_DETAILS VARIANT,
    RECORD_HASH STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SILVER.SILVER_RECIPE_EVIDENCE (
    EVIDENCE_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RAW_ID NUMBER,
    CONTENT_ID STRING,
    URL_TIKTOK STRING,
    SOURCE_TYPE STRING,
    SOURCE_NAME STRING,
    EVIDENCE_TEXT STRING,
    EVIDENCE_LENGTH NUMBER,
    EVIDENCE_QUALITY_SCORE FLOAT,
    EVIDENCE_QUALITY_CLASS STRING,
    IS_RECIPE_SIGNAL BOOLEAN,
    SOURCE_DETAILS VARIANT,
    RECORD_HASH STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CONTROL.RECIPE_PROCESSING_QUEUE (
    RAW_ID NUMBER,
    CONTENT_ID STRING,
    URL_TIKTOK STRING,
    CREATOR_USERNAME STRING,
    STATUS STRING,
    PRIORITY NUMBER DEFAULT 5,
    LAST_ERROR STRING,
    DISCOVERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_RECIPE_PROCESSING_QUEUE UNIQUE (RAW_ID)
);

CREATE OR REPLACE TABLE CONTROL.CREATOR_QUALITY_SCORE (
    CREATOR_USERNAME STRING,
    VIDEOS_SCANNED NUMBER DEFAULT 0,
    VIDEOS_ACCEPTED NUMBER DEFAULT 0,
    RECIPES_EXTRACTED NUMBER DEFAULT 0,
    FULL_RECIPES NUMBER DEFAULT 0,
    AVG_QUALITY_SCORE FLOAT DEFAULT 0,
    YIELD_RATE FLOAT DEFAULT 0,
    LAST_SCANNED_AT TIMESTAMP_NTZ,
    STATUS STRING DEFAULT 'active',
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_CREATOR_QUALITY_SCORE UNIQUE (CREATOR_USERNAME)
);
